### Send POST request with json body
POST http://localhost:8080/postPizza
Content-Type: application/json

{
  "name": "New",
  "calories": 1600,
  "image": "pepperoni.jpg",
  "price": 600,
  "weight": 1200,
  "diameter": 40,
  "composition": "asdasda"
}
