CREATE TABLE pizza
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    calories    DECIMAL,
    image       VARCHAR(255),
    price       DECIMAL,
    weight      DECIMAL,
    diameter    DECIMAL,
    composition VARCHAR(255),
    CONSTRAINT pk_pizza PRIMARY KEY (id)
);

CREATE TABLE userinfo
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number VARCHAR(255)                            NOT NULL,
    name   VARCHAR(255),
    CONSTRAINT pk_userinfo PRIMARY KEY (id)
);

ALTER TABLE userinfo
    ADD CONSTRAINT uc_userinfo_number UNIQUE (number);

CREATE TABLE "order"
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    status           INTEGER,
    payment          INTEGER,
    delivery         INTEGER,
    delivery_address VARCHAR(255),
    delivery_time    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES userinfo (id);

CREATE TABLE purchase
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pizza_id BIGINT                                  NOT NULL,
    order_id BIGINT                                  NOT NULL,
    number   INTEGER,
    CONSTRAINT pk_purchase PRIMARY KEY (id)
);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_PIZZA FOREIGN KEY (pizza_id) REFERENCES pizza (id);